#pragma once

#include "NativeGameplayTags.h"

namespace FragmentTag
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GridFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IconFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StackableFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConsumableFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(NameFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PrimaryStatFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(TypeFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(FlavorTextFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SellingPriceFragment)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RequiredLevelFragment)

	namespace StatMod
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_1)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_2)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(StatMod_3)
	}
}
